/* 
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms
*/
let sequence = [1, 2];
let nextNumber;
let sumOfEvens = 2;

for (i = 1; (sequence[i] + sequence[i-1]) < 4000000; i++) { // start loop to build Fibonacci sequence (array), max value 4000000
	nextNumber = sequence[i] + sequence[i-1]; 				// n = (n-1) + (n-2)
	sequence.push(nextNumber);								// add new number to sequence
	if (nextNumber % 2 == 0) {								// if new number is even
		sumOfEvens += nextNumber;							// add all even numbers to initial value of 2
	}
};
//console.log(sequence);
console.log('Sum of even numbers = ' + sumOfEvens);			// 4613732